version: '3.8'
services:
    mongo:
        image: mongo
        volumes:
            - mongo-data:/data/db
        networks:
            - backend
        ports:
            - 27017:27017

    express:
        restart: always
        image: mongo-express
        networks:
            - backend
        ports:
            - 8081:8081
networks:
    backend:

volumes:
    mongo-data:
